site_name: Rust For Linux
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition


nav:
  - 前言: 
    - '社区介绍': 'index.md'
    - '整体框架': 'framework.md'

  - 兼容性: 
    - '基础知识': 'compatibility/base.md'
    - '库兼容': 'compatibility/crate.md'
    - '类型兼容': 'compatibility/type.md'
    - 'RUST CALL C': 'compatibility/rust_call_c.md'

 # - 并发:


 # - RUST for Linux:

